name: Check style

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ty
    - name: Run code check
      uses: astral-sh/ruff-action@v3
    - name: Run type checking
      run: ty check
      